version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login-password --region us-east-2 |sudo docker login --username AWS --password-stdin 069589857775.dkr.ecr.us-east-2.amazonaws.com)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 069589857775.dkr.ecr.us-east-2.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 069589857775.dkr.ecr.us-east-2.amazonaws.com/youtube:latest
      - printf '[{"name":"ECSDEMOTASK","imageUri":"%s"}]' 069589857775.dkr.ecr.us-east-2.amazonaws.com/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
